name: Deploy to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and Push Docker Image
        run: |
            docker build -t abhitsahu/transit-backend:latest -f Dockerfile .
            docker push abhitsahu/transit-backend:latest

      - name: Deploy to AWS EC2
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            docker stop transit-backend || true
            docker rm transit-backend || true
            docker pull abhitsahu/transit-backend:latest
            docker run -d -p 8000:8000 --name transit-backend --env-file /home/ubuntu/.env abhitsahu/transit-backend:latest
