name: Deploy to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        run: echo "${{secrets.DOCKER_PASSWORD}}" | docker login -u "${{secrets.DOCKER_USERNAME}}" --password-stdin

      - name: Build and Push Docker Image
        run: |
            docker build -t abhitsahu/your-app:latest -f Dockerfile 
            docker push abhitsahu/your-app:latest

      - name: Deploy to AWS EC2
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            docker stop your-app || true
            docker rm your-app || true
            docker pull abhitsahu/your-app:latest
            docker run -d -p 8000:8000 --name your-app --env-file /home/ubuntu/.env abhitsahu/your-app:latest
